import {useEffect,useState} from 'react';
type Metrics={n:number;n_graded:number;n_funding_comparison:number;reef_funding_mae_bp:number|null;zero_funding_mae_bp:number|null;last_rate_funding_mae_bp:number|null;reef_direction_agreement:number|null;always_nonpositive_agreement:number|null;cost_mae_bp:number|null;n_predicted_positive:number;n_observed_positive:number;mean_paper_net_bp:number|null;reef_beats_zero_n:number;reef_beats_last_rate_n:number};
type Report={future_start_ms:number;future_cohort:Metrics;cutoff_ms:number;first_recorded_ms:number;last_recorded_ms:number;counts:Record<string,number>;summary:Metrics;n_batches:number;n_funding_batches:number;batch_equal_weight:Metrics;by_hold:Record<string,Metrics>;limits:string[];input_sha256:string};
const bp=(v:number|null)=>v===null?'Unavailable':`${v.toFixed(2)} bp`;
const percent=(v:number|null)=>v===null?'Unavailable':`${(v*100).toFixed(1)}%`;
const date=(v:number)=>new Date(v).toISOString().replace('T',' ').slice(0,16)+' UTC';
export function ConsecutiveValidation(){
 const [report,setReport]=useState<Report|null>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch(`${import.meta.env.BASE_URL}validation/consecutive-summary.json`,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{if(!controller.signal.aborted)setReport(d)}).catch(()=>{if(!controller.signal.aborted)setFailed(true)});return()=>controller.abort()},[]);
 if(!report)return <section id="consecutive-validation" className="shadow-desk"><h2>Consecutive case review</h2><p role="status">{failed?'The evaluation report could not be loaded. Reload this page to try again.':'Loading the consecutive case review…'}</p></section>;
 const s=report.summary;
 const compared=s.n_funding_comparison;
 return <section id="consecutive-validation" className="shadow-desk case-study" aria-label="Consecutive case validation">
  <div className="panel-top"><div><span className="eyebrow">Every case in this captured dataset</span><h2>Does Reef improve on a simple forecast?</h2></div><a className="outline-button" href={`${import.meta.env.BASE_URL}validation/consecutive-cases.json`} download>Download all results</a></div>
  <p className="case-intro">We evaluated all {s.n} scheduled paper records in this captured dataset, in the order they were recorded. {s.n_graded} have enough evidence to grade. The predictions were frozen before their paper outcomes; this comparison protocol was added after the historical outcomes.</p>
  <p className="ledger-note">Records from {date(report.first_recorded_ms)} to {date(report.last_recorded_ms)}. Evaluated through {date(report.cutoff_ms)}. {report.n_batches} entry batches; {report.n_funding_batches} contain comparable funding outcomes.</p>
  <div className="table-scroll"><table><caption>Mean absolute funding error. Lower is better. All three forecasts use the same {compared} cases.</caption><thead><tr><th>Forecast</th><th>Across cases</th><th>Equal weight per entry batch</th></tr></thead><tbody>
   <tr><td>Reef’s frozen estimate</td><td>{bp(s.reef_funding_mae_bp)}</td><td>{bp(report.batch_equal_weight.reef_funding_mae_bp)}</td></tr>
   <tr><td>Zero funding</td><td>{bp(s.zero_funding_mae_bp)}</td><td>{bp(report.batch_equal_weight.zero_funding_mae_bp)}</td></tr>
   <tr><td>Last settled rate continued</td><td>{bp(s.last_rate_funding_mae_bp)}</td><td>{bp(report.batch_equal_weight.last_rate_funding_mae_bp)}</td></tr>
  </tbody></table></div>
  <p>Compare the average error with how often each forecast wins. Reef beats zero funding on {s.reef_beats_zero_n} of {compared} cases and the last-rate forecast on {s.reef_beats_last_rate_n}. That does not establish statistical significance or profitable trading.</p>
  <details className="case-limits" open><summary>Incomplete cases remain in the record</summary><div className="table-scroll"><table><thead><tr><th>Outcome status</th><th>Records</th></tr></thead><tbody>{Object.entries(report.counts).map(([key,count])=><tr key={key}><td>{({graded:'Graded',pending:'Holding period not finished',missed_exit_window:'Missed exit window',insufficient_execution_or_funding_data:'Missing execution or funding data'} as Record<string,string>)[key]||key.replaceAll('_',' ')}</td><td>{count}</td></tr>)}</tbody></table></div><p>Missing outcomes can bias the comparison. They are excluded from error calculations, counted here, and retained in the download. A late exit is never substituted for a missing on-time exit.</p></details>
  <details className="case-limits"><summary>Results by holding period</summary><div className="table-scroll"><table><thead><tr><th>Hold</th><th>Comparable cases</th><th>Reef error</th><th>Zero funding error</th><th>Last rate error</th></tr></thead><tbody>{Object.entries(report.by_hold).map(([hold,m])=><tr key={hold}><td>{hold} day{hold==='1'?'':'s'}</td><td>{m.n_funding_comparison}</td><td>{bp(m.reef_funding_mae_bp)}</td><td>{bp(m.zero_funding_mae_bp)}</td><td>{bp(m.last_rate_funding_mae_bp)}</td></tr>)}</tbody></table></div><p>The full results include each instrument pair and holding period, every entry batch, and every record in chronological order.</p></details>
  <p className="ledger-note">The <a className="text-link" href={`${import.meta.env.BASE_URL}validation/protocol.json`} download>protocol for newly recorded cases</a> is fixed from {date(report.future_start_ms)}. So far, {report.future_cohort.n} new records and {report.future_cohort.n_graded} gradable outcomes fall after that boundary. Future outcomes require new observations; the historical results above are kept separate. The live research snapshot may contain newer records than this frozen evaluation.</p>
  <details className="case-limits"><summary>Direction, costs and staying out of the trade</summary><p>Reef’s net-outcome sign agreement is {percent(s.reef_direction_agreement)}. Always predicting a nonpositive outcome achieves {percent(s.always_nonpositive_agreement)} on the same cases. There were {s.n_predicted_positive} positive net estimates and {s.n_observed_positive} positive paper outcomes. A high agreement rate alone does not show forecasting skill.</p><p>Mean absolute execution-cost error is {bp(s.cost_mae_bp)}. Mean paper net P&amp;L is {bp(s.mean_paper_net_bp)} per reference notional. Staying out produces zero trading P&amp;L before idle-capital returns. These overlapping positions are not a portfolio simulation.</p></details>
  <details className="case-limits"><summary>Reproduce the calculation and understand its limits</summary><p>Download <a className="text-link" href={`${import.meta.env.BASE_URL}validation/consecutive-inputs.json`} download>the captured paper records and funding inputs</a> with the results. Put both files in <code>web/public/validation/</code> in the Reef source checkout and run <code>python src/prospective_validation.py --verify</code>. The verifier recomputes every status, forecast and aggregate, and checks the input hash. It does not authenticate the exchange data or verify Bitcoin proofs for the entire series.</p><ul>{report.limits.map(limit=><li key={limit}>{limit}</li>)}</ul><p>The last-rate baseline uses only rates strictly before entry, the frozen position weights and the prior settlement schedule. Cases without usable prior history are excluded from all three funding-error comparisons. Legacy infinite descriptive fields are encoded as strings in the input download; scoring fields remain numeric.</p></details>
 </section>;
}
