import {ReefLogo} from './Brand';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,BookOpen,Check,FileText,Search,X} from 'lucide-react';

export function AnalysisTabs({active,onChange}:{active:string;onChange:(tab:string)=>void}){
 const tabs=['Overview','Requirements','Stress tests','Source data'];
 return <div className="analysis-tabs" role="tablist" aria-label="Selected pair detail">{tabs.map((tab,index)=><button key={tab} id={`analysis-tab-${index}`} role="tab" aria-selected={active===tab} aria-controls="analysis-content" tabIndex={active===tab?0:-1} onClick={()=>onChange(tab)} onKeyDown={event=>{let next=index;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();onChange(tabs[next]);document.getElementById(`analysis-tab-${next}`)?.focus()}}>{tab}</button>)}</div>
}

export function SiteFooter(){
 return <footer className="site-footer"><div><ReefLogo/><p>Research funding income, trading costs and risk.</p></div><nav aria-label="Footer navigation"><a href="#/desk">Research desk</a><a href="#/desk/method">Method & glossary</a><a href="#/desk/evidence">Evidence & limitations</a><a href="#/privacy">Data & privacy</a></nav><p className="footer-disclosure">Historical estimates per reference notional. Reef does not place orders or simulate liquidation. A supported result is conditional on the model’s assumptions.</p></footer>
}

export function LandingSections(){
 const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{
  if(!root.current||window.matchMedia('(prefers-reduced-motion: reduce)').matches||!('IntersectionObserver' in window))return;
  const nodes=Array.from(root.current.querySelectorAll<HTMLElement>('section'));
  const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.12});
  nodes.forEach(node=>{node.classList.add('motion-ready');observer.observe(node)});
  return()=>{observer.disconnect();nodes.forEach(node=>node.classList.remove('motion-ready'))};
 },[]);
 return <div className="landing-motion" ref={root}>
 <section className="landing-section product-intro"><div className="intro-copy"><span className="eyebrow">A research desk for RWA perpetuals</span><h2>There’s more<br/> <em className="editorial-italic">beneath the yield.</em></h2><p>Two related instruments can show attractive funding. What matters is what remains after the hedge, the cost of both legs and the risk between them.</p></div><figure className="island-art"><div className="art-orbit" aria-hidden="true"/><div className="art-sculpture"><img src="/art/evidence-island.webp" width="1200" height="800" loading="lazy" decoding="async" alt="A sculptural island with green channels and exposed stone and glass layers"/></div></figure></section>
 <section className="landing-section product-window" aria-labelledby="window-title"><div className="landing-section-head"><span className="eyebrow">Inside the research desk</span><h2 id="window-title">Compare related instruments using the <em className="editorial-italic">same trade size and holding period.</em></h2></div><div className="product-panels"><article className="scenario-preview"><span className="preview-label">01 / Set the frame</span><div className="scenario-instruments"><span>QQQ</span><i>↔</i><span>TQQQ</span></div><p>Compare a Nasdaq 100 ETF with its leveraged counterpart.</p><dl><div><dt>Reference notional</dt><dd>$25,000</dd></div><div><dt>Holding period</dt><dd>30 days</dd></div></dl><a className="text-link" href="#/desk?pair=QQQ%2FTQQQ&size=25000&hold=30">Explore this scenario <ArrowUpRight size={16}/></a></article><article className="carry-preview"><span className="preview-label">02 / Look through the headline</span><h3>What remains<br/> after both legs?</h3><div className="carry-layers"><div><span>Gross funding carry</span><span>Start here</span></div><div><span>Execution costs</span><span>Subtract</span></div><div><span>Net carry estimate</span><span>Inspect</span></div><div><span>Residual risk + uncertainty</span><span>Challenge</span></div></div></article></div></section>
 <section className="landing-section workflow-section" aria-labelledby="workflow-title"><div className="landing-section-head"><span className="eyebrow">The workflow</span><h2 id="workflow-title">Start with a trade you want to understand.</h2></div><ol className="workflow-steps" aria-label="How to use Reef"><li><span className="step-index">01 / Frame</span><Search size={23}/><h3>Choose the pair, size and holding period.</h3><p>Set the dollar amount and how long you would hold the position. Reef applies those inputs to every pair so you can compare them.</p></li><li><span className="step-index">02 / Challenge</span><BookOpen size={23}/><h3>Test what happens when the assumptions change.</h3><p>Ask what happens if funding reverses or trading costs rise. Compare the stress estimate with the original calculation.</p></li><li><span className="step-index">03 / Record</span><FileText size={23}/><h3>Save the results for your own review.</h3><p>Check when the data was captured and which assumptions were used, then download your questions and results.</p></li></ol></section>
 <section className="landing-section decision-section"><div><span className="eyebrow">Evidence before confidence</span><h2>A positive estimate can still have <em className="editorial-italic">weak evidence.</em></h2><p>Read the verdict alongside the estimate. A trade can show positive carry while the funding data is too uncertain to support a conclusion.</p></div><dl className="verdict-key"><div><dt><span className="badge supported"><i/>Supported</span></dt><dd>The modelled risk-adjusted estimate clears the point threshold and its funding-only interval excludes zero.</dd></div><div><dt><span className="badge unproven"><i/>Unproven</span></dt><dd>The point threshold clears, but the funding-only interval still crosses zero.</dd></div><div><dt><span className="badge unfavourable"><i/>Unfavourable</span></dt><dd>The modelled risk-adjusted estimate falls below the point threshold.</dd></div></dl></section>
 <section className="landing-section evidence-promise"><figure className="archive-art"><div className="art-orbit" aria-hidden="true"/><div className="art-sculpture"><img src="/art/research-archive-cutout.webp" width="1000" height="667" loading="lazy" decoding="async" alt="Layered archival paper under forest-green glass with a carved island seal"/></div></figure><div className="archive-copy"><span className="eyebrow">The research record</span><h2>Check how a result was calculated <em className="editorial-italic">and what happened afterwards.</em></h2><div className="evidence-pillars"><article><span>01</span><div><h3>Versioned calculations</h3><p>The same inputs produce the same figures. The language model explains those calculations.</p></div></article><article><span>02</span><div><h3>Paper outcomes</h3><p>Recorded estimates are compared with later order books and funding payments in paper trades.</p></div></article><article><span>03</span><div><h3>Timestamped records</h3><p>Bitcoin anchors establish when a record existed. They do not certify accuracy or guarantee a return.</p></div></article></div><a className="text-link" href="#/desk/evidence">Review evidence and limits <ArrowRight size={16}/></a></div></section>
 <section className="landing-close"><span className="eyebrow">Research first</span><h2>Take a closer look<br/> <em className="editorial-italic">before you trade.</em></h2><a className="pill-button" href="#/desk">Open the research desk <ArrowUpRight size={18}/></a></section>
 </div>
}

export function DeskGuide({step,onStart,onInspect,onChallenge,onFinish}:{step:number;onStart:()=>void;onInspect:()=>void;onChallenge:()=>void;onFinish:()=>void}){
 const [open,setOpen]=useState(()=>{try{return localStorage.getItem('reef-guide-open-2')==='1'}catch{return false}});
 useEffect(()=>{try{localStorage.setItem('reef-guide-open-2',open?'1':'0')}catch{}},[open]);
 const steps=[['Read the selected result','Start with the estimate over your chosen hold. Then read the verdict and its explanation.'],['Inspect what limits the result','Read the carry needed, shortest qualifying hold and remaining risk in Requirements.'],['Challenge the assumption','Your question is prepared in the notebook. Review its context, then press Investigate. Nothing is submitted automatically.'],['Keep a dated record','Review the result and its sources. Use Export research in the notebook to keep your questions and evidence.']];
 return <section className={`desk-guide ${open||step?'open':''}`} aria-label="Getting started"><div className="guide-header"><span><BookOpen size={17}/>{step?`Guided example · step ${step} of 4`:'New to Reef? Try one recorded scenario.'}</span><div className="guide-actions">{step?<button className="text-link" onClick={onFinish}>{step===4?'Finish example':'Exit example'}<X size={14}/></button>:<><button className="text-link" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{open?'Hide guide':'Read guide'}</button><button className="outline-button" onClick={onStart}>Start guided example <ArrowRight size={14}/></button></>}</div></div>{step>0?<div className="guided-step" role="status"><div><strong>{steps[step-1][0]}</strong><p>{steps[step-1][1]}</p></div>{step===1?<button className="outline-button" onClick={onInspect}>Inspect requirements <ArrowRight size={14}/></button>:step===2?<div><button className="outline-button" onClick={onChallenge}>Prepare example question <ArrowRight size={14}/></button><small>Starts a new notebook and retains your current record for restoration.</small></div>:step===3?<a className="outline-button" href="#research-notebook" onClick={event=>{event.preventDefault();document.getElementById('notebook-question')?.focus({preventScroll:true});document.getElementById('research-notebook')?.scrollIntoView({behavior:'auto',block:'start'})}}>Review the question <ArrowRight size={14}/></a>:<button className="outline-button" onClick={onFinish}>Finish example <Check size={14}/></button>}</div>:open&&<><ol><li><span>1</span><div><strong>Frame the trade</strong><p>Choose reference size and hold. Size is not your margin deposit.</p></div></li><li><span>2</span><div><strong>Read the answer</strong><p>Check the holding-period return, verdict and limiting assumption.</p></div></li><li><span>3</span><div><strong>Challenge and record</strong><p>Review the notebook context, ask a question and export the dated result.</p></div></li></ol><p className="guide-note"><Check size={14}/> No trading permissions needed. Examples use historical evidence, not forecasts.</p></>}</section>
}

export function Glossary(){
 return <section className="glossary"><div><span className="eyebrow">Reading the desk</span><h2>Terms used in the desk</h2></div><div>{[
 ['Reference notional','The dollar size used to measure the trade and its return. It is not your margin deposit, account balance or a recommendation to trade that size.'],
 ['Basis points (bp)','One basis point is 0.01 percentage points. A net estimate of 10 bp is 0.10% of reference notional over the stated hold.'],
 ['Annualised estimate','A historical estimate scaled to a year for comparison. It assumes the observed carry persists; it is not a forecast or a compounded return.'],
 ['Hedge and residual risk','The hedge ratio is fitted on earlier prices. It reduces shared price exposure, while the difference between the instruments still creates residual risk.'],
 ['Sharpe proxy and confidence interval','The modelled Sharpe proxy compares net carry with estimated residual risk. Its 95% interval reflects funding uncertainty under fixed hedge, costs and residual volatility. It is not realised trading Sharpe and does not capture all uncertainty.'],
 ['Supported result','The point estimate clears Reef’s 0.50 threshold and the funding-only 95% interval excludes zero. These are research criteria, not a guarantee of profit or execution.']
 ].map(([term,definition])=><details key={term}><summary>{term}</summary><p>{definition}</p></details>)}</div></section>
}

export function PrivacyPage(){
 return <main id="privacy-content" tabIndex={-1} className="desk-shell privacy-page"><div className="section-heading"><span className="eyebrow">Data & privacy</span><h1>How Reef handles your data.</h1><p>Reef works without an account or wallet connection. Here is how the research workflow handles your inputs.</p></div><div className="privacy-sections"><section><h2>Saved on this device</h2><p>Your saved pairs, guide preference, latest research notebook and one previous notebook use this browser’s local storage. Each notebook retains up to 200 turns. Other people using the same browser profile may be able to read them. Export before clearing browser data.</p></section><section><h2>Optional account notebooks</h2><p>When accounts are available, you can sign in with a passkey and choose to save a separate copy online. Your name, passkey public credential and saved notebooks are stored by Reef’s account service. Your device handles the biometric or PIN check; Reef does not receive your fingerprint or face data. Account notebooks also keep a draft on this device. A verified recovery email is optional when email recovery is available. Keep an exported copy of important research.</p></section><section><h2>When you submit a question</h2><p>Your question, scenario, snapshot identifier and recent conversation context are sent to Reef’s research service. When available, Qwen receives the question and relevant context to resolve the request and interpret the recorded evidence. Avoid entering personal information, account details, credentials or confidential trading information.</p></section><section><h2>Exports and shared links</h2><p>Exports contain your questions, scenarios and the dated research results. Review them before sharing. Scenario links contain only public instrument names, reference size and holding period; they do not include notebook questions or an account.</p></section><section><h2>Service boundaries</h2><p>The application does not request wallet access or exchange trading credentials, and does not place orders. Hosting and model providers may process request metadata under their own policies. This page does not claim that provider-side requests or logs are never retained.</p></section></div><a className="pill-button" href="#/desk">Back to research <ArrowRight size={16}/></a></main>
}
