import {CloudNotebookPanel,useCloudNotebook} from './CloudNotebook';
import {cleanCopy} from './copy';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Download,RefreshCw,MessageSquare,Info} from 'lucide-react';
import {holdReturn} from './researchPresentation';
import type {FormEvent} from 'react';

type Context={pairs:string[];size:number;hold:number;stress:string|null};
type Cell={verdict:string;gross_bp:number;cost_bp:number;net_bp:number;sharpe:number;ci_lo:number|null;ci_hi:number|null;risk_bp:number;requires?:{binding:string;bp_per_day_now:number;bp_per_day_needed:number;min_hold_days:number|null}};
type Card={pair:string;size:number;hold:number;cell:Cell|null;history_days:number;direction:string;stress:{key:string;label:string;value:number|null;unit:string}|null};
type Reply={schema:string;question:string;snapshot_utc:string;model_version:string;context:Context;planner:string;interpreter:string|null;commentary:{finding:string;tradeoff:string;next_check:string}|null;note:string;result:{title:string;cards:Card[];leading:{pair:string;metric:string}|null;disclosures:string[]}};
type Notebook={snapshot_utc:string;context:Context;turns:Reply[]};
const STORAGE='reef-research-notebook-1';
const BACKUP='reef-research-notebook-previous-1';
function savedNotebook(key:string):Notebook|null{try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(typeof saved?.snapshot_utc==='string'&&Array.isArray(saved.turns)&&saved.turns.length<=200&&Array.isArray(saved.context?.pairs)&&saved.context.pairs.every((p:unknown)=>typeof p==='string')&&Number.isFinite(saved.context.size)&&Number.isFinite(saved.context.hold)&&saved.turns.every((turn:Reply)=>turn.schema==='reef-research-1'&&typeof turn.question==='string'&&Array.isArray(turn.result?.cards)))return saved}catch{}return null}
const value=(n:number|null|undefined,decimals=1)=>n===null||n===undefined?'Unavailable':n.toFixed(decimals);
const verdict=(s:string)=>s==='SUPPORTED'?'Supported':s==='UNPROVEN'?'Unproven':'Unfavourable';
const stressLabel=(stress:string|null)=>stress?({half_funding:'Funding halves',funding_reversal:'Funding reverses',cost_plus_50:'Execution costs rise by half',risk_plus_50_sharpe:'Residual risk rises by half'} as Record<string,string>)[stress]||'Recorded stress':'Base assumptions';

function ResearchResult({reply}:{reply:Reply}){
 const {result}=reply;
 const [expanded,setExpanded]=useState(false);
 return <div className="research-result"><h3>{cleanCopy(result.title)}</h3><p className="result-scenario">${reply.context.size.toLocaleString('en-US')} reference · {reply.context.hold}-day hold · {stressLabel(reply.context.stress)} · Snapshot {reply.snapshot_utc}</p>
 {!result.cards.length?<p className="research-empty">Try the same scenario without the Supported filter, or change the holding period.</p>:<div className="table-scroll"><table className="research-comparison"><caption>Estimates use the same size and holding period.{reply.context.stress&&' Stress results do not have a recalculated verdict or confidence interval.'}</caption><thead><tr><th>Recorded evidence</th>{result.cards.map(card=><th key={card.pair}>{card.pair}<small>{card.direction}</small></th>)}</tr></thead><tbody>
 {result.cards.some(card=>card.stress?.unit==='bp over hold')&&<tr className="research-stress-row"><th>{result.cards.find(card=>card.stress?.unit==='bp over hold')?.stress?.label} · net over the hold<small>Stress point estimate; no recomputed verdict</small></th>{result.cards.map(card=><td key={card.pair}>{card.stress?.unit==='bp over hold'&&card.stress.value!=null?holdReturn(card.stress.value):'Unavailable'}</td>)}</tr>}
 <tr><th>Base estimated net over the hold · %</th>{result.cards.map(card=><td key={card.pair}>{card.cell?holdReturn(card.cell.net_bp):'Unavailable'}</td>)}</tr>
 <tr><th>Base verdict</th>{result.cards.map(card=><td key={card.pair}>{card.cell?<span className={`badge ${card.cell.verdict.toLowerCase()}`}>{verdict(card.cell.verdict)}</span>:'Book cannot support this size'}</td>)}</tr>
 <tr><th>Binding constraint</th>{result.cards.map(card=><td key={card.pair}>{({cost:'Execution cost',risk:'Residual risk',evidence:'Funding uncertainty'} as Record<string,string>)[card.cell?.requires?.binding||'']||'Unavailable'}</td>)}</tr>
 {expanded&&<>
 {([['Gross carry · bp','gross_bp'],['Execution cost · bp','cost_bp'],['Residual risk · bp','risk_bp'],['Modelled Sharpe proxy','sharpe']] as const).map(([label,key])=><tr key={key}><th>{label}</th>{result.cards.map(card=><td key={card.pair}>{value(card.cell?.[key],key==='sharpe'?2:1)}</td>)}</tr>)}
 <tr><th>Funding-only 95% interval</th>{result.cards.map(card=><td key={card.pair}>{card.cell?.ci_lo!=null&&card.cell?.ci_hi!=null?`${value(card.cell.ci_lo,2)} to ${value(card.cell.ci_hi,2)}`:'Unavailable'}</td>)}</tr>

 <tr><th>Carry needed · bp/day</th>{result.cards.map(card=><td key={card.pair}>{value(card.cell?.requires?.bp_per_day_needed,2)}<small>Base estimate · other assumptions fixed</small></td>)}</tr>
 <tr><th>Shortest qualifying hold</th>{result.cards.map(card=><td key={card.pair}>{card.cell?.requires?card.cell.requires.min_hold_days?`${card.cell.requires.min_hold_days} days`:'None within the tested year':'Unavailable'}</td>)}</tr>
 </>}
 {result.cards.some(card=>card.stress?.unit==='Sharpe proxy')&&<tr className="research-stress-row"><th>{result.cards[0]?.stress?.label}<small>Stress point estimate only</small></th>{result.cards.map(card=><td key={card.pair}>{value(card.stress?.value,card.stress?.unit==='Sharpe proxy'?2:1)}<small>{card.stress?.unit}</small></td>)}</tr>}
 </tbody></table></div>}
 {result.cards.length>0&&<button className="text-link research-detail-toggle" aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?'Hide calculation details':'Show calculation details'}</button>}
 {result.leading&&<p className="research-leading"><strong>{result.leading.pair}</strong> has the highest {result.leading.metric.toLowerCase()} among these recorded scenarios. Read the constraints before drawing a conclusion.</p>}
 {reply.commentary?<div className="research-interpretation"><span className="eyebrow">AI interpretation · {reply.interpreter}</span>{Object.entries(reply.commentary).map(([label,text])=><p key={label}><strong>{label==='finding'?'Finding':label==='tradeoff'?'Trade-off':'Next check'}</strong>{cleanCopy(text)}</p>)}</div>:<p className="research-fallback"><Info size={14}/>{cleanCopy(reply.note)}</p>}
 <details className="research-sources"><summary>Evidence sources and assumptions</summary><p>Snapshot {reply.snapshot_utc} · model {reply.model_version} · task resolved by {reply.planner}. Financial figures are copied from the Python export. Browser notebook turns are not Bitcoin-anchored.</p><ul>{result.disclosures.map(text=><li key={text}>{cleanCopy(text)}</li>)}</ul><p>Instrument data: Bitget captured books, funding and hourly prices. This comparison does not establish that the instruments are economically interchangeable.</p></details>
 </div>
}

export function ResearchConversation({snapshotUtc,pair,size,hold,onRefresh,onResolved,exampleRequest,onContextChange,guideStep,onFinishGuide,onShowContext}:{snapshotUtc:string;pair:string;size:number;hold:number;onRefresh:()=>void;onResolved:(question:string,context:Context)=>void;onShowContext:(context:Context)=>void;guideStep:number;onFinishGuide:()=>void;exampleRequest:{id:number;text:string}|null;onContextChange:(context:Context & {snapshot_utc:string})=>void}){
 const initial=():Notebook=>savedNotebook(STORAGE)||{snapshot_utc:snapshotUtc,context:{pairs:[pair],size,hold,stress:null},turns:[]};
 const [notebook,setNotebook]=useState<Notebook>(initial),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [exportPreview,setExportPreview]=useState(''),[previousNotebook,setPreviousNotebook]=useState<Notebook|null>(()=>savedNotebook(BACKUP));
 const [retryAllowed,setRetryAllowed]=useState(true);
 const cloud=useCloudNotebook(notebook,(record:Notebook)=>{abort.current?.abort();setBusy(false);setNotebook(record)},()=>setNotebook(savedNotebook(STORAGE)||{snapshot_utc:snapshotUtc,context:{pairs:[pair],size,hold,stress:null},turns:[]}));
 const abort=useRef<AbortController|null>(null),latest=useRef<HTMLDivElement>(null);
 const previousSelection=useRef({pair,size,hold});
 const appliedExample=useRef<number|null>(null);
 const [draftNotice,setDraftNotice]=useState(''),[storageWarning,setStorageWarning]=useState('');
 const stale=notebook.snapshot_utc!==snapshotUtc;
 const differentSelection=!!notebook.context.stress||notebook.context.pairs.length!==1||notebook.context.pairs[0]!==pair||notebook.context.size!==size||notebook.context.hold!==hold;
 useEffect(()=>{try{if(!cloud.storageKey){localStorage.setItem(STORAGE,JSON.stringify(notebook));setStorageWarning('')}}catch{setStorageWarning('This browser could not save your notebook. Export a copy before leaving this page.')}},[notebook,cloud.storageKey]);
 useEffect(()=>{try{if(previousNotebook)localStorage.setItem(BACKUP,JSON.stringify(previousNotebook));else localStorage.removeItem(BACKUP)}catch{}},[previousNotebook]);
 useEffect(()=>()=>abort.current?.abort(),[]);
 useEffect(()=>{if(stale&&!notebook.turns.length)setNotebook({snapshot_utc:snapshotUtc,context:{pairs:[pair],size,hold,stress:null},turns:[]})},[stale,snapshotUtc,notebook.turns.length,pair,size,hold]);
 useEffect(()=>{onContextChange({...notebook.context,snapshot_utc:notebook.snapshot_utc})},[notebook.context,notebook.snapshot_utc,onContextChange]);
 useEffect(()=>{const previous=previousSelection.current;previousSelection.current={pair,size,hold};if(previous.pair===pair&&previous.size===size&&previous.hold===hold)return;if(notebook.turns.length)return;if(abort.current){abort.current.abort();abort.current=null;setBusy(false);setError('The selected scenario changed. Ask again using the current context.')}if(!stale)setNotebook(n=>({...n,context:{pairs:[pair],size,hold,stress:null}}))},[pair,size,hold,stale,notebook.turns.length]);
 useEffect(()=>{if(!exampleRequest||appliedExample.current===exampleRequest.id)return;appliedExample.current=exampleRequest.id;cloud.detach();abort.current?.abort();abort.current=null;setBusy(false);setError('');setExportPreview('');if(notebook.turns.length)setPreviousNotebook(cloud.storageKey?savedNotebook(STORAGE):notebook);setNotebook({snapshot_utc:snapshotUtc,context:{pairs:[pair],size,hold,stress:null},turns:[]});setQuestion(current=>current.trim()?current:exampleRequest.text);setDraftNotice('Guided example ready. Any existing draft is retained. Review the question and scenario before submitting.');requestAnimationFrame(()=>{document.getElementById('notebook-question')?.focus({preventScroll:true});document.getElementById('research-notebook')?.scrollIntoView({behavior:'auto',block:'start'})})},[exampleRequest]);

 function reset(){cloud.detach();abort.current?.abort();abort.current=null;setBusy(false);setError('');setExportPreview('');if(notebook.turns.length)setPreviousNotebook(cloud.storageKey?savedNotebook(STORAGE):notebook);setNotebook({snapshot_utc:snapshotUtc,context:{pairs:[pair],size,hold,stress:null},turns:[]})}
 function restore(){if(!previousNotebook)return;cloud.detach();abort.current?.abort();abort.current=null;setBusy(false);setError('');setExportPreview('');setNotebook(previousNotebook);setPreviousNotebook(cloud.storageKey?savedNotebook(STORAGE):notebook.turns.length?notebook:null)}
 async function ask(text:string){
  if(busy||stale)return;if(notebook.turns.length>=200){setError('This notebook has reached 200 turns. Save or export it, then start a new notebook.');return;}
  setError('');setRetryAllowed(true);setDraftNotice('');setBusy(true);setQuestion(text);
  const controller=new AbortController();abort.current=controller;const timeout=setTimeout(()=>controller.abort(),55000);
  try{const response=await fetch('/api/research',{method:'POST',headers:{'content-type':'application/json'},signal:controller.signal,body:JSON.stringify({question:text,context:notebook.context,snapshot_utc:notebook.snapshot_utc,history:notebook.turns.slice(-3).flatMap(turn=>[{role:'user',content:turn.question},{role:'assistant',content:JSON.stringify(turn.context)}])})});const reply=await response.json();if(!response.ok)throw Object.assign(Error(reply.error||'Research is unavailable. Retry this question.'),{status:response.status});if(reply.schema!=='reef-research-1'||reply.snapshot_utc!==notebook.snapshot_utc)throw Error('The response does not match this notebook’s frozen snapshot. Start a new notebook.');if(controller.signal.aborted)return;setNotebook(n=>({...n,context:reply.context,turns:[...n.turns,reply]}));setQuestion('');onResolved(text,reply.context);requestAnimationFrame(()=>latest.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'}))}
  catch(e){if(abort.current!==controller)return;setRetryAllowed(![400,409,413].includes((e as {status?:number}).status||0));setError(e instanceof Error&&e.name!=='AbortError'?e.message:'Research timed out. Your previous turns are retained; retry the question.')}
  finally{clearTimeout(timeout);if(abort.current===controller){setBusy(false);abort.current=null}}
 }
 function submit(e:FormEvent){e.preventDefault();void ask(question)}
 function download(){const report={...notebook,exported_utc:new Date().toISOString(),limits:['A research notebook, not an order or a forecast.','Notebook turns are not Bitcoin-anchored.','All comparisons use the stated frozen snapshot.']};const encoded=JSON.stringify(report,null,2);setExportPreview(encoded);const url=URL.createObjectURL(new Blob([encoded],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='reef-research-notebook.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const suggestions=notebook.turns.length?['What if funding reverses?','Now use a 7-day hold','What would need to change?','Remove the stress test']:[`Compare QQQ/TQQQ with SMH/SOXL at $${size.toLocaleString('en-US')} for ${hold} days`,`Rank the strongest setups at $${size.toLocaleString('en-US')} for ${hold} days`,'Explain this setup’s constraint'];
 return <section id="research-notebook" className="research-notebook" aria-label="Research conversation"><header><h2 className="sr-only">Notebook actions</h2><div className="notebook-actions"><button className="outline-button" onClick={reset}><RefreshCw size={14}/> New notebook</button><button className="outline-button" onClick={download} disabled={!notebook.turns.length} title={!notebook.turns.length?'Submit a question to create an export':undefined}><Download size={14}/> Export research</button></div></header>
 {storageWarning&&<p className="query-message" role="alert">{storageWarning}</p>}<CloudNotebookPanel cloud={cloud} hasResearch={notebook.turns.length>0}/>{previousNotebook&&<p className="notebook-undo" role="status">Previous notebook available in this browser. <button className="text-link" disabled={busy} onClick={restore}>Restore previous notebook</button></p>}
 <p className="question-context-label">{stale?'Saved notebook context':'Context for your next question'}</p><div className="research-context" aria-label={stale?'Saved notebook context':'Context for your next question'}><span>{notebook.context.pairs.join(' · ')||'All tracked pairs'}</span><span>${notebook.context.size.toLocaleString()} reference</span><span>{notebook.context.hold}-day hold</span><span>{stressLabel(notebook.context.stress)}</span><small>Frozen snapshot · {notebook.snapshot_utc}</small></div>
 {differentSelection&&!stale&&<p className="notebook-selection-warning">Your next question uses the notebook context above. Explore currently uses {pair} · ${size.toLocaleString('en-US')} · {hold} days · base assumptions. <button className="text-link" disabled={busy} onClick={()=>setNotebook(n=>({...n,context:{pairs:[pair],size,hold,stress:null}}))}>Use the Explore scenario</button>{notebook.context.pairs[0]&&<button className="text-link" disabled={busy} onClick={()=>onShowContext(notebook.context)}>Analyse {notebook.context.pairs[0]}</button>}</p>}
 {stale&&<p className="query-message" role="status">This saved notebook uses an older snapshot. You can export it; start a new notebook to research the latest evidence.</p>}
 {draftNotice&&<p className="query-message" role="status">{draftNotice}</p>}
 <form hidden={stale} onSubmit={submit}><div className="question-field"><label htmlFor="notebook-question">{notebook.turns.length?'Ask a follow-up':'What would you like to investigate?'}</label><input id="notebook-question" aria-describedby="notebook-input-hint" autoComplete="off" maxLength={700} value={question} onChange={e=>setQuestion(e.target.value)} placeholder={notebook.turns.length?'Change the hold, compare another pair, or test funding…':`Compare QQQ/TQQQ and SMH/SOXL at $${size.toLocaleString()} for ${hold} days`} disabled={busy||stale}/></div><button className="pill-button" disabled={busy||stale||question.trim().length<3} type="submit">{busy?'Investigating…':'Investigate'}<ArrowRight size={16}/></button></form>
 <p hidden={stale} id="notebook-input-hint" className="input-hint">Uses the notebook context above. Naming another pair, size, hold or stress in your question changes that context; earlier results keep their recorded scenario.</p>
 {error&&<div className="query-message" role="alert"><Info size={15}/><span>{error}</span><button className="outline-button" disabled={busy||stale||question.trim().length<3} onClick={()=>retryAllowed?void ask(question):document.getElementById('notebook-question')?.focus()}>{retryAllowed?'Retry question':'Edit question'}</button>{/snapshot|evidence|refresh/i.test(error)&&<button className="text-link" onClick={onRefresh}>Refresh evidence</button>}</div>}
 <div hidden={stale} className="research-suggestions">{suggestions.map(text=><button key={text} disabled={busy||stale} onClick={()=>void ask(text)}>{text}<ArrowRight size={12}/></button>)}</div>
 <p className="research-privacy">{cloud.storageKey?'Account notebook with a draft on this device':'Guest notebook saved in this browser'} · Questions and context sent to Qwen when available · <a href="#/privacy">Data & privacy</a></p>
 <p className="sr-only" role="status">{busy?'Research in progress.':notebook.turns.length?`Latest research result ready. ${notebook.turns.length} ${notebook.turns.length===1?'turn':'turns'} saved.`:'Ready for your first research question.'}</p>
 <div className="research-thread" aria-busy={busy}><div ref={latest}/>{busy&&<div className="research-loading"><p>Resolving your question and checking the recorded evidence…</p><div className="ai-skeleton"/><div className="ai-skeleton short"/></div>}{!notebook.turns.length&&!busy&&<div className="notebook-empty"><MessageSquare size={21}/><p>Ask about a pair or compare two trades.</p><span>Choose a suggested comparison above, or investigate the selected pair.</span></div>}{notebook.turns.map((reply,index)=>index===notebook.turns.length-1?<article className="research-turn" key={`${index}-${reply.question}`}><div className="research-question"><MessageSquare size={16}/><p>{cleanCopy(reply.question)}</p><small>Latest · turn {index+1}</small></div><ResearchResult reply={reply}/></article>:null)}{notebook.turns.length>1&&<div className="previous-turns"><h3>Earlier questions</h3>{notebook.turns.slice(0,-1).map((reply,index)=><details key={`${index}-${reply.question}`}><summary><span>Turn {index+1}</span>{cleanCopy(reply.question)}</summary><ResearchResult reply={reply}/></details>)}</div>}{notebook.turns.length>=200&&<p className="input-hint">This notebook has reached 200 turns. Save or export it, then start another notebook. Earlier turns are retained.</p>}</div>
 {guideStep===4&&notebook.turns.length>0&&<div className="guided-inline"><p>Your example has a dated result. Keep its questions, context and sources together.</p><div className="report-actions"><button className="outline-button" onClick={download}><Download size={14}/> Export example notebook</button><button className="text-link" onClick={onFinishGuide}>Finish guided example</button></div></div>}
 {exportPreview&&<details className="research-export" open><summary>Dated research export</summary><p>Your JSON download was requested. If this browser blocks downloads, select and save the same content below.</p><pre tabIndex={0} aria-label="Exported notebook JSON">{cleanCopy(exportPreview)}</pre></details>}
 </section>
}
